export const components = [
  { name: 'autocomplete', type: 'others' },
  { name: 'button', type: 'basic' },
  { name: 'checkbox', type: 'basic' },
  { name: 'checkbox-button', type: 'basic' },
  { name: 'color', type: 'others' },
  { name: 'date', type: 'basic' },
  { name: 'input', type: 'basic' },
  { name: 'number', type: 'basic' },
  { name: 'password', type: 'basic' },
  { name: 'radio', type: 'basic' },
  { name: 'radio-button', type: 'basic' },
  { name: 'rate', type: 'others' },
  { name: 'select', type: 'others' },
  { name: 'slider', type: 'others' },
  { name: 'switch', type: 'others' },
  { name: 'textarea', type: 'basic' },
  { name: 'text', type: 'basic' },
  { name: 'time-select', type: 'others' },
  { name: 'time-picker', type: 'others' },
  { name: 'date-picker', type: 'others' },
  { name: 'date-range', type: 'others' },
  { name: 'datetime', type: 'others' },
  { name: 'datetime-range' },
  { name: 'transfer', type: 'others' },
  { name: 'cascader', type: 'others' },
  { name: 'upload-image', type: 'others' }
]

export const formAttrDefault = {
  inline: false,
  disabled: false,
  readonly: false,
  isShowLabel: true,
  isDialog: false,
  isShowSubmitBtn: true,
  isShowBackBtn: null,
  isShowResetBtn: false,
  isShowCancelBtn: null,
  isResponsive: true,
  submitBtnText: '提交',
  cancelBtnText: '取消',
  backBtnText: '返回',
  resetBtnText: '重置',
  labelWidth: null,
  labelPosition: null,
  span: null,
  formBtnSize: null
}
